### ISSUE TITLE
This is a great library, when will it support MacOS

### ISSUE THREAD

**Issue by chengpan168** [rakuyoMo/JSONPreview#4]
This is a great library, when will it support MacOS

**Comment by rakuyoMo** [comment]
> This is a great library, when will it support MacOS

This is a great idea, let's discuss it further: 

`JSONPreview` can now be used with programs running as `Mac Catalyst`.

do you mean introducing `AppKit` under macOS? Something like the following

```swift
#if os(macOS)
import AppKit
#else
import UIKit
#endif
```

**Comment by chengpan168** [comment]
Ok, one of my open source software written with Swiftui uses SwiftyJSON to format JSON, but there is no highlighting. I am a beginner Apple developer, so I don't know whether such integration is possible in Swiftui, thank you very much

**Comment by rakuyoMo** [comment]
> Ok, one of my open source software written with Swiftui uses SwiftyJSON to format JSON, but there is no highlighting. I am a beginner Apple developer, so I don't know whether such integration is possible in Swiftui, thank you very much

Then what you need should be support for both **SwiftUI** and **macOS**.

But unfortunately I know very little about both, especially SwiftUI...

I noticed that `redis-pro`'s to-do list has plans for iPad support, so I have a suggestion: try using `Mac Catalyst` technology.

**It allows applications built on iOS to run on macOS.** Only a few code changes are required, such as support for keyboard shortcuts. Since you're using SwiftUI, it shouldn't be difficult to switch your existing code to the iOS platform either.

The future `JSONPreview` may support SwiftUI in a better way, **but I don't think it will come soon**, possibly later this year.

As for support for macOS, **that's not in my plans for now**. Thanks to wrapping, there isn't a lot of logic scattered throughout the `JSONPreview` view code, which should be good news for getting it to support macOS, but the problem is that I don't have time to get into `AppKit` at the moment...

Or maybe someone who sees this issue can provide a PR to help make it better. I'd appreciate it.

**Comment by chengpan168** [comment]
Okay, thank you very much, I will try
